
# package and data --------------------------------------------------------

library(tidyverse)
library(sf)
library(mapsapi)

## intersection
intersection = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/Intersections.shp',
                       stringsAsFactors = F) %>% 
  select(-FID0, -Legs) %>% 
  st_zm()

## mid-block
city_network = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/Road_network_with_highway.shp',
                       stringsAsFactors = F) %>% 
  select(OFT, STREET_TYP) %>% 
  st_zm() %>% 
  mutate(STREET_TYP = ifelse(is.na(STREET_TYP), 'Local', STREET_TYP))

## connection between intersection and mid-block
int_block = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/Intersection_intersect_with_block.shp',
                    stringsAsFactors = F) %>% 
  st_drop_geometry() %>% 
  select(JuncID, OFT)

## mid-block centroid
network_centroid = st_centroid(city_network) %>% 
  select(-STREET_TYP)

# near function -----------------------------------------------------------

near = function(sf_x, sf_y) {
  near_index = st_nearest_feature(sf_x, sf_y)
  near_distance = unclass(st_distance(sf_x, sf_y[near_index, ], by_element = T))
  sf_near = cbind(sf_x, near_index, near_distance) %>% 
    arrange(near_index, near_distance) %>% 
    st_drop_geometry()
  return(sf_near)
}

# pedestrian and bicycle crash assembling ---------------------------------

## crashes from 2016 to 2017
## crashes after 2016 have a different code system
for (year in 2016:2017) {
  
  ## file location
  file_loc = 'C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/PedCrash_crash_data_from_DPS/0517/'
  
  ## crashes that happened in the city of Minneapolis
  acc = read.csv(paste(file_loc, year, '/mn-', year, '-acc.txt', sep = ''),  sep = '\t', stringsAsFactors = F) %>% 
    filter(XCOORD != '.') %>% 
    mutate(CITY = as.character(CITY),
           latitude = as.numeric(XCOORD),
           longitude = as.numeric(YCOORD)) %>%
    filter(CITY == '2585') %>%
    select(ACCN, ACCDATE, latitude, longitude)
  
  ## indicate pedestrian and bicycle in the vehicle file
  veh = read.csv(paste(file_loc, year, '/mn-', year, '-veh.txt', sep = ''),  sep = '\t', stringsAsFactors = F) %>% 
    select(ACCN, VEHTYPE)
  ped_crash_index = veh %>% 
    mutate(PedCrashI = ifelse(VEHTYPE == 53, 1, 0)) %>% 
    filter(PedCrashI == 1) %>% 
    select(ACCN, PedCrashI) %>% 
    distinct(ACCN, .keep_all = T)
  bike_crash_index = veh %>% 
    mutate(BikeCrashI = ifelse(VEHTYPE == 54, 1, 0)) %>% 
    filter(BikeCrashI == 1) %>% 
    select(ACCN, BikeCrashI) %>% 
    distinct(ACCN, .keep_all = T)
    
  ## merge vehicle file to crash file and select pedestrian and bicycle crashes
  ped_crash = acc %>% 
    left_join(ped_crash_index, by = 'ACCN') %>% 
    filter(PedCrashI == 1) %>% 
    select(-PedCrashI)
  
  bike_crash = acc %>% 
    left_join(bike_crash_index, by = 'ACCN') %>% 
    filter(BikeCrashI == 1) %>% 
    select(-BikeCrashI)
  
  ## combine crashes from different years
  if (year == 2016) {
    ped_crash_1617 = ped_crash
    bike_crash_1617 = bike_crash
  } else {
    ped_crash_1617 = rbind(ped_crash_1617, ped_crash)
    bike_crash_1617 = rbind(bike_crash_1617, bike_crash)
  }
}

## create pedestrian and bicycle crash sf data
ped_crash_1617 = ped_crash_1617 %>% 
  select(ACCN, latitude, longitude) %>% 
  st_as_sf(coords = c('longitude', 'latitude'), crs = 4326) %>% 
  st_transform(crs = 26915)

bike_crash_1617 = bike_crash_1617 %>% 
  select(ACCN, latitude, longitude) %>% 
  st_as_sf(coords = c('longitude', 'latitude'), crs = 4326) %>% 
  st_transform(crs = 26915)

## crashes from 2005 to 2015

## all crashes
for (year in 2005:2015) {
  
  ## file location
  file_loc = 'C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/PedCrash_crash_data_from_DPS/0517/'
  
  ## crashes that happened in the city of Minneapolis
  acc = read.csv(paste(file_loc, year, '/mn-', year, '-acc.txt', sep = ''),  sep = '\t', stringsAsFactors = F) %>% 
    filter(latitude != 0) %>% 
    mutate(CITY = as.character(CITY),
           latitude = as.numeric(latitude),
           longitude = as.numeric(longitude)) %>%
    filter(CITY == '2585') %>%
    select(ACCN, ACCDATE, latitude, longitude)
  
  ## combine crashes from different years
  if (year == 2005) {
    acc_0515 = acc
  } else {
    acc_0515 = rbind(acc_0515, acc)
  }
  
}

## delete duplicated observations
## remove last four digits from the current ACCN variable
acc_0515 = acc_0515 %>% 
  distinct(ACCN, .keep_all = T) %>% 
  mutate(ACCN = floor(ACCN/1E4))

## read pedestrian and bicycle crashes generated by the city of Minneapolis
ped_crash_0515 = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/PedCrash_crash_data_from_DPS/0517/PedCrash_Ped_0515/Minneapolis_Ped_crash_0515.shp')
bike_crash_0515 = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/PedCrash_crash_data_from_DPS/0517/PedCrash_Bike_0515/Minneapolis_Bike_crash_0515.shp')

## merge crash information to pedestrian or bicycle crashes by the city of Minneapolis
## method: inner join 
ped_crash_0515 = ped_crash_0515 %>% 
  st_zm() %>% 
  rename(ACCN = INCIDENT) %>% 
  inner_join(acc_0515, by = 'ACCN') %>% 
  select(ACCN)

bike_crash_0515 = bike_crash_0515 %>% 
  st_zm() %>% 
  rename(ACCN = INCIDENT) %>% 
  inner_join(acc_0515, by = 'ACCN') %>% 
  filter(!is.na(latitude)) %>% 
  select(ACCN)

## combine all pedestrian or bicycle crashes
ped_crash_0517 = rbind(ped_crash_0515, ped_crash_1617)
bike_crash_0517 = rbind(bike_crash_0515, bike_crash_1617)

# crash number at intersection and mid-blocks -------------------------------------------------------

## road function
## Local: Local, Activity Center, Parkway, Null, NA
## Secondary: Commerce, Community, Industrial, Neighborhood
## Main: Commuter
## Highway: Highway
road_function = city_network %>% 
  st_drop_geometry() %>% 
  mutate(class = case_when(STREET_TYP == 'Local' | STREET_TYP == 'Activity Center' |
                             STREET_TYP == 'Parkway' | STREET_TYP == 'Null' ~ 'Local',
                           STREET_TYP == 'Commerce' | STREET_TYP == 'Community' |
                             STREET_TYP == 'Industrial' | STREET_TYP == 'Neighborhood' ~ 'Secondary',
                           STREET_TYP == 'Commuter' ~ 'Main',
                           STREET_TYP == 'Highway' ~ 'Highway',
                           T ~ 'Local'),
         value = 1) %>% 
  right_join(int_block, by = 'OFT') %>%
  select(-OFT, -STREET_TYP) %>% 
  group_by(JuncID) %>% 
  summarise(MainNum = sum(class == 'Main'),
            SecondNum = sum(class == 'Secondary'),
            LocalNum = sum(class == 'Local'),
            HighwayNum = sum(class == 'Highway'))

## join road function to intersection
## calculate the number of road segments for different road classes
## set dummy variables for different road classes
intersection_without_highway = intersection %>% 
  left_join(road_function, by = 'JuncID') %>% 
  filter(!(MainNum == 0 & SecondNum == 0 & LocalNum == 0 & HighwayNum > 0)) %>% 
  mutate(Main = ifelse(MainNum > 0, 1, 0),
         Second = ifelse(SecondNum > 0, 1, 0),
         Highway = ifelse(HighwayNum > 0, 1, 0),
         Local = ifelse(LocalNum > 0, 1, 0))

## select intersections connected only to with local roads (or highways)
## create 15-meter buffers for these intersections
intersection_15m_buffer = intersection_without_highway %>% 
  filter(SecondNum == 0 & MainNum == 0) %>% 
  st_buffer(dist = 15) %>% 
  select(JuncID)

## select intersections connected to main roads or secondary roads
## create 35-meter buffers for these intersections
intersection_35m_buffer = intersection_without_highway %>% 
  filter(SecondNum > 0 | MainNum > 0) %>% 
  st_buffer(dist = 35) %>% 
  select(JuncID)

## combine 15-meter and 35-meter buffers together
intersection_buffer = rbind(intersection_15m_buffer, intersection_35m_buffer)

## assign pedestrian crashes to intersection buffers
## assign rest of the pedestrian crashes to mid-blocks
## remove highway from sample
intersection_ped_crash = st_intersection(ped_crash_0517, intersection_buffer) %>% 
  st_drop_geometry() %>% 
  group_by(JuncID) %>% 
  summarise(PedCrashNum = n())

block_ped_crash = st_join(ped_crash_0517, intersection_buffer) %>% 
  filter(is.na(JuncID)) %>% 
  select(-JuncID)

near_index = st_nearest_feature(block_ped_crash, city_network)
# near_distance = unclass(st_distance(block_ped_crash, city_network[near_index, ], by_element = T))
block_ped_crash = city_network[near_index, ] %>% 
  filter(STREET_TYP != 'Highway') %>% 
  st_drop_geometry() %>% 
  group_by(OFT) %>% 
  summarise(PedCrashNum = n())

## assign bicycle crashes to intersection buffers
## assign rest of the bicycle crashes to mid-blocks
## remove highway from sample
intersection_bike_crash = st_intersection(bike_crash_0517, intersection_buffer) %>% 
  st_drop_geometry() %>% 
  group_by(JuncID) %>% 
  summarise(BikeCrashNum = n())

block_bike_crash = st_join(bike_crash_0517, intersection_buffer) %>% 
  filter(is.na(JuncID)) %>% 
  select(-JuncID)

near_index = st_nearest_feature(block_bike_crash, city_network)
# near_distance = unclass(st_distance(block_ped_crash, city_network[near_index, ], by_element = T))
block_bike_crash = city_network[near_index, ] %>% 
  filter(STREET_TYP != 'Highway') %>% 
  st_drop_geometry() %>% 
  group_by(OFT) %>% 
  summarise(BikeCrashNum = n())

# pedestrian, bicycle, vehicle exposure -----------------------------------

## calculate the pedestrian and bicycle count for each location
## based on mean values over 8 years
count = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/count location/Final_Count_Locations.shp', stringsAsFactors = F) %>% 
  mutate(ID = rownames(.)) %>% 
  select(ID, BIKE_EDT_2:PED_EDT_27) %>% 
  rename(Bike_2007 = BIKE_EDT_2,
         Bike_2008 = BIKE_EDT_3,
         Bike_2009 = BIKE_EDT_4,
         Bike_2010 = BIKE_EDT_5,
         Bike_2011 = BIKE_EDT_6,
         Bike_2012 = BIKE_EDT_7,
         Bike_2013 = BIKE_EDT_8,
         Bike_2014 = BIKE_EDT_9,
         Ped_2007 = PED_EDT_20,
         Ped_2008 = PED_EDT_21,
         Ped_2009 = PED_EDT_22,
         Ped_2010 = PED_EDT_23,
         Ped_2011 = PED_EDT_24,
         Ped_2012 = PED_EDT_25,
         Ped_2013 = PED_EDT_26,
         Ped_2014 = PED_EDT_27) %>% 
  mutate(Ped_2007 = ifelse(Ped_2007 == '-', 0, Ped_2007),
         Ped_2007 = as.numeric(Ped_2007)) %>% 
  st_drop_geometry() %>% 
  na_if(0) %>% 
  mutate(PedCount = rowMeans(select(., starts_with('Ped')), na.rm = T),
         BikeCount = rowMeans(select(., starts_with('Bike')), na.rm = T)) %>% 
  select(ID, PedCount, BikeCount)

## merge pedestrian and bicycle count data to location file
count_location = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/count location/Final_Count_Locations.shp', stringsAsFactors = F) %>% 
  mutate(ID = row.names(.)) %>% 
  select(ID) %>% 
  left_join(count, by = 'ID')
  
## assign pedestrian and bicycle count data to nearest city network
## if one mid-block matches two or more count location, choose the closet one
road_near_count_location = near(count_location, city_network) %>% 
  distinct(near_index, .keep_all = T) %>% 
  select(-ID, -near_distance)
  
city_network_count = city_network %>% 
  st_drop_geometry() %>% 
  mutate(ID = as.numeric(row.names(.))) %>% 
  left_join(road_near_count_location, by = c('ID'='near_index')) %>% 
  select(-STREET_TYP, -ID)

## AADT
AADT = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/PedCrash_data_from_DPW/StreetsPlanEvaluation.gdb',
               layer = 'AADT_OFT',
               stringsAsFactors = F) %>% 
  st_transform(crs = 26915) %>% 
  select(OFT, STREET_TYPE, AADT_MPLS) %>% 
  mutate(STREET_TYPE = ifelse(STREET_TYPE == '', 'Local', STREET_TYPE)) %>% 
  st_drop_geometry() %>% 
  na_if(0) %>% 
  mutate(AADT_MPLS = case_when(
    STREET_TYPE == 'Local' & is.na(AADT_MPLS) ~ round(mean(filter(., STREET_TYPE == 'Local')$AADT_MPLS, na.rm = T)),
    STREET_TYPE == 'Activity Center' & is.na(AADT_MPLS) ~ round(mean(filter(., STREET_TYPE == 'Activity Center')$AADT_MPLS, na.rm = T)),
    STREET_TYPE == 'Commerce' & is.na(AADT_MPLS) ~ round(mean(filter(., STREET_TYPE == 'Commerce')$AADT_MPLS, na.rm = T)),
    STREET_TYPE == 'Community' & is.na(AADT_MPLS) ~ round(mean(filter(., STREET_TYPE == 'Community')$AADT_MPLS, na.rm = T)),
    STREET_TYPE == 'Commuter' & is.na(AADT_MPLS) ~ round(mean(filter(., STREET_TYPE == 'Commuter')$AADT_MPLS, na.rm = T)),
    STREET_TYPE == 'Highway' & is.na(AADT_MPLS) ~ round(mean(filter(., STREET_TYPE == 'Highway')$AADT_MPLS, na.rm = T)),
    STREET_TYPE == 'Industrial' & is.na(AADT_MPLS) ~ round(mean(filter(., STREET_TYPE == 'Industrial')$AADT_MPLS, na.rm = T)),
    STREET_TYPE == 'Neighborhood' & is.na(AADT_MPLS) ~ round(mean(filter(., STREET_TYPE == 'Neighborhood')$AADT_MPLS, na.rm = T)),
    STREET_TYPE == 'Parkway' & is.na(AADT_MPLS) ~ round(mean(filter(., STREET_TYPE == 'Parkway')$AADT_MPLS, na.rm = T)),
    T ~ as.numeric(AADT_MPLS)
  )) %>% 
  select(-STREET_TYPE)

city_network_count = city_network_count %>% 
  left_join(AADT, by = 'OFT') %>% 
  mutate(AADT_MPLS = ifelse(is.na(AADT_MPLS), 1, AADT_MPLS))

## estimated pedestrian and bicycle counts
## for each mid-block, find a nearest estimation location
estimation_location = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/reminneapoliscountdata/Model_Extrapolation_Points.shp') %>% 
  rename(BikeEstCount = BikeDis,
         PedEstCount = PedDis) %>% 
  select(PedEstCount, BikeEstCount)

city_network_estimation = near(city_network, estimation_location) %>% 
  left_join(mutate(st_drop_geometry(estimation_location), ID = as.numeric(row.names(estimation_location))),
            by = c('near_index'='ID')) %>% 
  select(OFT, PedEstCount, BikeEstCount)

city_network_count = city_network_count %>% 
  left_join(city_network_estimation, by = 'OFT')

## for estimated pedestrian or bicycle count, use actual count to replace it when actual count is available
## calculate log(PedEstCount), log(BikeEstCount), and log(AADT_MPLS)
## add a dummy variable IfActual to indicate the available of actual count
city_network_count = city_network_count %>% 
  mutate(PedEstCount = ifelse(!is.na(PedCount), PedCount, PedEstCount),
         BikeEstCount = ifelse(!is.na(BikeCount), BikeCount, BikeEstCount)) %>% 
  mutate(LnPedCount = log(PedEstCount),
         LnBikeCount = log(BikeEstCount),
         LnAADT = log(AADT_MPLS)) %>% 
  mutate(IfActual = ifelse(!is.na(PedCount), 1, 0))

## aggregate mid-block level counts to intersections
## if one intersection has two or more links with pedestrian or bicycle count
## then calculate the pedestrian or bicycle count for that intersection
## otherwise, the intersection has no available pedestrian or bicycle count data
intersection_count = int_block %>% 
  left_join(city_network_count, by = 'OFT') %>% 
  group_by(JuncID) %>% 
  summarise(LegNum = n(),
            NumOfPedObs = sum(!is.na(PedCount)),
            NumOfBikeObs = sum(!is.na(BikeCount)),
            PedCount = ifelse(NumOfPedObs <= 1, NA, 0.5*(LegNum/NumOfPedObs)*sum(PedCount, na.rm = T)),
            BikeCount = ifelse(NumOfBikeObs <= 1, NA, 0.5*(LegNum/NumOfBikeObs)*sum(BikeCount, na.rm = T)),
            AADT_MPLS = 0.5*mean(AADT_MPLS),
            PedEstCount = 0.5*mean(PedEstCount),
            BikeEstCount = 0.5*mean(BikeEstCount)) %>% 
  mutate(PedCount = ifelse(is.nan(PedCount), NA, PedCount),
         BikeCount = ifelse(is.nan(BikeCount), NA, BikeCount)) %>% 
  mutate(PedEstCount = ifelse(!is.na(PedCount), PedCount, PedEstCount),
         BikeEstCount = ifelse(!is.na(BikeCount), BikeCount, BikeEstCount)) %>% 
  mutate(LnPedCount = log(PedEstCount),
         LnBikeCount = log(BikeEstCount),
         LnAADT = log(AADT_MPLS)) %>% 
  mutate(IfActual = ifelse(!is.na(PedCount), 1, 0)) %>% 
  select(-NumOfPedObs, -NumOfBikeObs)

# BE ----------------------------------------------------------------------

## population density and job density at the block levels
## use block levels for larger variance in these two variables
job = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/job.shp',
              stringsAsFactors = F) %>% 
  st_drop_geometry() %>% 
  rename(job = c000)

pop = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/Twin_cities_pop_2010.shp',
              stringsAsFactors = F) %>% 
  select(POP10, BLOCKID10) %>% 
  left_join(job, by = c('BLOCKID10'='id') ) %>% 
  mutate(job = ifelse(is.na(job), 0, job)) %>% 
  mutate(area = unclass(st_area(.))/1e4) %>% 
  mutate(PopDen = POP10/area,
         JobDen = job/area) %>% 
  select(PopDen, JobDen)

city_network_density = st_intersection(network_centroid, pop) %>% 
  st_drop_geometry() %>% 
  select(OFT, PopDen, JobDen) %>% 
  distinct(OFT, .keep_all = T)

intersection_density = st_intersection(intersection, pop) %>% 
  st_drop_geometry() %>% 
  select(JuncID, PopDen, JobDen)

## number of intersections in 400-meter buffers
twin_cities_intersections = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/intersections_in_metroarea.shp')

city_network_int_number = st_buffer(network_centroid, dist = 400) %>% 
  st_intersection(twin_cities_intersections, .) %>% 
  st_drop_geometry() %>% 
  group_by(OFT) %>% 
  summarise(IntNum = n())

intersection_int_number = st_buffer(intersection, dist = 400) %>% 
  st_intersection(twin_cities_intersections, .) %>% 
  st_drop_geometry() %>% 
  group_by(JuncID) %>% 
  summarise(IntNum = n())

## number of transit stops in 30-meter buffers
transit_stops = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/transit_stops.shp')

city_network_transit_stop_number = st_buffer(network_centroid, dist = 30) %>% 
  st_intersection(transit_stops, .) %>% 
  st_drop_geometry() %>% 
  group_by(OFT) %>% 
  summarise(TraStpNum = n())

intersection_transit_stop_number = st_buffer(intersection, dist = 400) %>% 
  st_intersection(transit_stops, .) %>% 
  st_drop_geometry() %>% 
  group_by(JuncID) %>% 
  summarise(TraStpNum = n())

## distance to downtown Minneapolis
destination = data.frame(longitude = -93.270869,
                          latitude = 44.976314) %>% 
  st_as_sf(coords = c('longitude', 'latitude'), crs = 4326) %>% 
  st_transform(crs = 26915)

city_network_distance = city_network %>% 
  st_drop_geometry() %>% 
  cbind(., unclass(st_distance(network_centroid, destination))/1000) %>% 
  rename(DisToMin = 'unclass(st_distance(network_centroid, destination))/1000') %>% 
  select(OFT, DisToMin)

intersection_distance = intersection %>% 
  st_drop_geometry() %>% 
  cbind(., unclass(st_distance(intersection, destination))/1000) %>% 
  rename(DisToMin = 'unclass(st_distance(intersection, destination))/1000') %>% 
  select(JuncID, DisToMin)


## merge intersection BE together
intersection_BE = intersection %>% 
  st_drop_geometry() %>% 
  left_join(intersection_density, by = 'JuncID') %>% 
  left_join(intersection_int_number, by = 'JuncID') %>% 
  left_join(intersection_transit_stop_number, by = 'JuncID') %>% 
  left_join(intersection_distance, by = 'JuncID')

## merge mid-block BE together
city_network_BE = city_network %>% 
  select(-STREET_TYP) %>% 
  st_drop_geometry() %>% 
  left_join(city_network_density, by = 'OFT') %>% 
  left_join(city_network_int_number, by = 'OFT') %>% 
  left_join(city_network_transit_stop_number, by = 'OFT') %>% 
  left_join(city_network_distance, by = 'OFT')


# land use ----------------------------------------------------------------

# ## land use
# ## land use type:
# ## Commercial: 1
# ## Office: 2
# ## Industrial: 3
# ## Open space: 4
# ## Other: 5
# landuse = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/Landuse.shp') %>% 
#   mutate(Landuse_type = case_when(
#     Landuse == 1 ~ 'Comm',
#     Landuse == 2 ~ 'Off',
#     Landuse == 3 ~ 'Indu',
#     Landuse == 4 ~ 'OpSpace',
#     Landuse == 5 ~ 'Other'
#   )) %>% 
#   select(Landuse_type) %>% 
#   st_make_valid()
# 
# ## share of land use areas and land use entropy
# ## the area of buffers should use the area calculated by st_area() function
# ## its value is slightly smaller than the area calculated by equation pi*100^2
# ## it shows that the buffers are not a complete circle
# city_network_landuse = st_buffer(network_centroid, dist = 100) %>% 
#   st_intersection(., landuse) %>% 
#   mutate(area = unclass(st_area(.))) %>% 
#   st_drop_geometry() %>% 
#   group_by(OFT, Landuse_type) %>% 
#   summarise(PerArea = sum(area)/31401.57,
#             plnp = PerArea*log(PerArea)) %>% 
#   pivot_wider(names_from = Landuse_type,
#               values_from = c(PerArea, plnp),
#               values_fill = list(PerArea = 0)) %>% 
#   as_tibble() %>% ## convert to a tibble
#   mutate(K = rowSums(!is.na(select(., starts_with('plnp'))))) %>% 
#   mutate(LandMix = ifelse(K == 1, 0,
#                           -rowSums(select(., starts_with('plnp')), na.rm = T)/log(K))) %>% 
#   mutate(sum = rowSums(select(., starts_with('PerArea')))) %>% 
#   select(OFT, starts_with('PerArea'), LandMix)
# 
# intersection_landuse = st_buffer(intersection, dist = 100) %>% 
#   st_intersection(., landuse) %>% 
#   mutate(area = unclass(st_area(.))) %>% 
#   st_drop_geometry() %>% 
#   group_by(JuncID, Landuse_type) %>% 
#   summarise(PerArea = sum(area)/31401.57,
#             plnp = PerArea*log(PerArea)) %>% 
#   pivot_wider(names_from = Landuse_type,
#               values_from = c(PerArea, plnp),
#               values_fill = list(PerArea = 0)) %>% 
#   as_tibble() %>% 
#   mutate(K = rowSums(!is.na(select(., starts_with('plnp'))))) %>% 
#   mutate(LandMix = ifelse(K == 1, 0,
#                           -rowSums(select(., starts_with('plnp')), na.rm = T)/log(K))) %>% 
#   mutate(sum = rowSums(select(., starts_with('PerArea')))) %>% 
#   select(JuncID, starts_with('PerArea'), LandMix)
# 
# write.csv(city_network_landuse, './result/city_network_landuse.csv', row.names = F)
# write.csv(intersection_landuse, './result/intersection_landuse.csv', row.names = F)

# geographic location ------------------------------------------------------

## downtown area
## mid-block can only be counted as in the downtown area
## when more than 50% of its length is located in the downtown area
city_network_in_downtown = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/Downtown_boundary.shp') %>% 
  st_transform(crs = 26915) %>% 
  summarise() %>% 
  st_intersection(mutate(city_network, original_distance = unclass(st_length(city_network))), .) %>% 
  mutate(PerDist = unclass(st_length(.))/original_distance) %>% 
  st_drop_geometry() %>% 
  group_by(OFT) %>% 
  summarise(PerDist =  sum(PerDist)) %>% 
  mutate(Downtown = ifelse(PerDist > 0.5, 1, 0)) %>% 
  select(OFT, Downtown)

intersection_in_downtown = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/Downtown_boundary.shp') %>% 
  st_transform(crs = 26915) %>% 
  summarise() %>% 
  st_intersection(intersection, .) %>% 
  st_drop_geometry() %>% 
  mutate(Downtown = 1) %>% 
  select(JuncID, Downtown)

## city area
## mid-block can only be counted as in the city area
## when more than 50% of its length is located in the city area
city_network_in_city = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/City_boundary.shp') %>% 
  st_intersection(mutate(city_network, original_distance = unclass(st_length(city_network))), .) %>% 
  mutate(PerDist = unclass(st_length(.))/original_distance) %>% 
  st_drop_geometry() %>% 
  group_by(OFT) %>% 
  summarise(PerDist =  sum(PerDist)) %>% 
  mutate(City = ifelse(PerDist > 0.5, 1, 0)) %>% 
  select(OFT, City)

intersection_in_city = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/City_boundary.shp') %>% 
  st_intersection(intersection, .) %>% 
  st_drop_geometry() %>% 
  mutate(City = 1) %>% 
  select(JuncID, City)

## ACP50 area
city_network_in_ACP50 = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/ACP50_boundary.shp') %>% 
  st_intersection(mutate(city_network, original_distance = unclass(st_length(city_network))), .) %>% 
  mutate(PerDist = unclass(st_length(.))/original_distance) %>% 
  st_drop_geometry() %>% 
  group_by(OFT) %>% 
  summarise(PerDist =  sum(PerDist)) %>% 
  mutate(ACP50 = ifelse(PerDist > 0.5, 1, 0)) %>% 
  select(OFT, ACP50)

intersection_in_ACP50 = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/ACP50_boundary.shp') %>% 
  st_intersection(intersection, .) %>% 
  st_drop_geometry() %>% 
  mutate(ACP50 = 1) %>% 
  select(JuncID, ACP50)

## merge city network geographic location together
city_network_location = city_network %>% 
  select(-STREET_TYP) %>% 
  st_drop_geometry() %>% 
  left_join(city_network_in_downtown, by = 'OFT') %>% 
  left_join(city_network_in_city, by = 'OFT') %>% 
  left_join(city_network_in_ACP50, by = 'OFT')

## merge intersection geographic location together
intersection_location = intersection %>% 
  st_drop_geometry() %>% 
  left_join(intersection_in_downtown, by = 'JuncID') %>% 
  left_join(intersection_in_city, by = 'JuncID') %>% 
  left_join(intersection_in_ACP50, by = 'JuncID')

# Traffic facilities ------------------------------------------------------

## sidewalk
## if NUM_WALKS > 0 then it has a sidewalk
city_network_sidewalk = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/PedCrash_data_from_DPW/StreetsPlanEvaluation.gdb',
                                layer = 'Sidewalk_Gap_OFT',
                                stringsAsFactors = F) %>% 
  st_drop_geometry() %>% 
  mutate(Sidewalk = ifelse(NUM_WALKS > 0, 1, 0)) %>% 
  select(OFT, Sidewalk)

intersection_sidewalk = int_block %>% 
  left_join(city_network_sidewalk, by = 'OFT') %>% 
  group_by(JuncID) %>% 
  summarise(SidewalkNum = sum(Sidewalk, na.rm = T)) %>% 
  mutate(Sidewalk = ifelse(SidewalkNum > 0, 1, 0)) %>% 
  select(JuncID, Sidewalk)

## bicycle lane
## if OnStr_BikeFac = Yes, then it has a bicycle lane 
city_network_bikelane = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/PedCrash_data_from_DPW/StreetsPlanEvaluation.gdb',
                                layer = 'BicycleTypes_OFT',
                                stringsAsFactors = F) %>% 
  st_drop_geometry() %>% 
  mutate(Bikelane = ifelse(OnStr_BikeFac == 'Yes', 1, 0)) %>% 
  select(OFT, Bikelane)

intersection_bikelane = int_block %>% 
  left_join(city_network_bikelane, by = 'OFT') %>% 
  group_by(JuncID) %>% 
  summarise(BikelaneNum = sum(Bikelane, na.rm = T)) %>% 
  mutate(Bikelane = ifelse(BikelaneNum > 0, 1, 0)) %>% 
  select(JuncID, Bikelane)

## trail
## if the 10-meter buffer of one intersection touches one or more trail
## then the intersection has a trail
intersection_trail = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/Trail.shp') %>% 
  st_intersection(st_buffer(intersection, dist = 10)) %>% 
  mutate(length = unclass(st_length(.))) %>% 
  st_drop_geometry() %>% 
  group_by(JuncID) %>% 
  summarise(Trail = 1)

## streetlight
intersection_streetlight = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/street_light.shp') %>% 
  st_intersection(st_buffer(intersection, dist = 30)) %>% 
  st_drop_geometry() %>% 
  group_by(JuncID) %>% 
  summarise(StLightNum = n()) %>% 
  mutate(StLight = ifelse(StLightNum > 0, 1, 0))

## traffic signal
intersection_traffic_signal = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/Reproduction_of_crash_model_construction/traffic_signals.shp') %>% 
  st_intersection(st_buffer(intersection, dist = 30)) %>% 
  st_drop_geometry() %>% 
  group_by(JuncID) %>% 
  summarise(TraSignalNum = n()) %>% 
  mutate(TraSignal = ifelse(TraSignalNum > 0, 1, 0))

## main road and secondary road
city_network_road_function = city_network %>% 
  st_drop_geometry() %>% 
  mutate(class = case_when(STREET_TYP == 'Local' | STREET_TYP == 'Activity Center' |
                             STREET_TYP == 'Parkway' | STREET_TYP == 'Null' ~ 'Local',
                           STREET_TYP == 'Commerce' | STREET_TYP == 'Community' |
                             STREET_TYP == 'Industrial' | STREET_TYP == 'Neighborhood' ~ 'Secondary',
                           STREET_TYP == 'Commuter' ~ 'Main',
                           STREET_TYP == 'Highway' ~ 'Highway',
                           T ~ 'Local')) %>% 
  mutate(Main = ifelse(class == 'Main', 1, 0),
         Second = ifelse(class == 'Secondary', 1, 0),
         Local = ifelse(class == 'Local', 1, 0)) %>% 
  select(OFT, (Main:Local))

intersection_road_function = int_block %>% 
  left_join(city_network_road_function, by = 'OFT') %>% 
  group_by(JuncID) %>% 
  summarise(MainNum = sum(Main),
            SecondNum = sum(Second),
            LocalNum = sum(Local)) %>% 
  mutate(Main = ifelse(MainNum > 0, 1, 0),
         Second = ifelse(SecondNum > 0, 1, 0),
         Local = ifelse(LocalNum > 0, 1, 0))

## travel width
travel_width = st_read('C:/UMN/Projects/PdBkCrsh/PdBkCrsh_data_analysis/data_backup/lane_width.shp') %>% 
  st_zm() %>% 
  select(TRAVEL_WID)

city_network_travel_width = near(network_centroid, travel_width) %>%
  left_join(mutate(st_drop_geometry(travel_width), id = as.numeric(row.names(travel_width))),
            by = c('near_index' = 'id')) %>% 
  rename(LaneWidth = TRAVEL_WID) %>% 
  select(OFT, LaneWidth)

intersection_travel_width = int_block %>% 
  left_join(city_network_travel_width, by = 'OFT') %>% 
  group_by(JuncID) %>% 
  summarise(LaneWidth = max(LaneWidth))

## detailed road class

# detailed_road_class = st_read('C:/UMN/Projects/PdBkCrsh/PdBkCrsh_data_analysis/data_backup/road_func.shp') %>% 
#   st_zm() %>% 
#   select(DESCRIPTIO) %>% 
#   rename(dClass = DESCRIPTIO)
# 
# city_network_detailed_road_class = near(network_centroid, detailed_road_class) %>%
#   left_join(mutate(st_drop_geometry(detailed_road_class), id = as.numeric(row.names(detailed_road_class))),
#             by = c('near_index' = 'id')) %>% 
#   select(OFT, dClass)
# 
# city_network_road_class_comparison = city_network_detailed_road_class %>% 
#   left_join(st_drop_geometry(city_network), by = 'OFT') %>% 
#   mutate(class = case_when(STREET_TYP == 'Local' | STREET_TYP == 'Activity Center' |
#                              STREET_TYP == 'Parkway' | STREET_TYP == 'Null' ~ 'Local',
#                            STREET_TYP == 'Commerce' | STREET_TYP == 'Community' |
#                              STREET_TYP == 'Industrial' | STREET_TYP == 'Neighborhood' ~ 'Secondary',
#                            STREET_TYP == 'Commuter' ~ 'Main',
#                            STREET_TYP == 'Highway' ~ 'Highway')) %>% 
#   mutate(dClass = case_when(dClass == 'Principal Arterial - Interstate' | dClass == 'Principal Arterial - Other' | dClass == 'Principal Arterial - Other Freeways and Expressways' ~ 'PA',
#                             dClass == 'Minor Arterial' ~ 'MA',
#                             dClass == 'Major Collector' | dClass == 'Minor Collector' ~ 'MC',
#                             dClass == 'Local' ~ 'LC')) %>% 
#   select(OFT, class, dClass)

## merge city network traffic facilities together
city_network_traffic_facility = city_network %>% 
  select(-STREET_TYP) %>% 
  st_drop_geometry() %>% 
  left_join(city_network_sidewalk, by = 'OFT') %>% 
  left_join(city_network_bikelane, by = 'OFT') %>% 
  left_join(city_network_road_function, by = 'OFT') %>% 
  left_join(city_network_travel_width, by = 'OFT')

## merge intersection traffic facilities together
intersection_traffic_facility = intersection %>% 
  st_drop_geometry() %>% 
  left_join(intersection_sidewalk, by = 'JuncID') %>% 
  left_join(intersection_bikelane, by = 'JuncID') %>% 
  left_join(intersection_trail, by = 'JuncID') %>% 
  left_join(intersection_streetlight, by = 'JuncID') %>% 
  left_join(intersection_traffic_signal, by = 'JuncID') %>% 
  left_join(intersection_road_function, by = 'JuncID') %>% 
  left_join(intersection_travel_width, by = 'JuncID')

# SE ----------------------------------------------------------------------

SE = foreign::read.dbf('C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/shp_society_census_acs/CensusACSBlockGroup.dbf',
                       as.is = T) %>% 
  mutate(PerChild = (M_0_4+M_5_9+M_10_14+F_0_4+F_5_9+F_10_14)/POPTOTAL,
         PerOld = AGE65UP/POPTOTAL,
         PerMan = rowSums(select(., starts_with('M_')))/POPTOTAL,
         HHSize = AVGHHSIZE,
         AvgVeh = VEHICLESN/HHTOTAL,
         PerWhite = WHITENH/POPTOTAL,
         Poverty = POV185RATE) %>% 
  select(GEOG_UNIT, (PerChild:Poverty))

city_network_SE = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/shp_society_census2010realign/Census2010RealignBlockGroup.shp',
                          stringsAsFactors = F) %>% 
  st_intersection(network_centroid, .) %>% 
  st_drop_geometry() %>% 
  left_join(SE, by = c('GEOID'='GEOG_UNIT')) %>% 
  select(OFT, (PerChild:Poverty))

intersection_SE = st_read('C:/UMN/Projects/PedCrash/PedCrash_GIS/data_backup/shp_society_census2010realign/Census2010RealignBlockGroup.shp',
                          stringsAsFactors = F) %>% 
  st_intersection(intersection, .) %>% 
  st_drop_geometry() %>% 
  left_join(SE, by = c('GEOID'='GEOG_UNIT')) %>% 
  select(JuncID, (PerChild:Poverty))

# merge all variables -----------------------------------------------------

## read land use variables
city_network_landuse = read_csv('./result/city_network_landuse.csv')
intersection_landuse = read_csv('./result/intersection_landuse.csv')

## intersection result
intersection_result = intersection_without_highway %>% 
  st_drop_geometry() %>% 
  select(JuncID) %>% 
  left_join(intersection_ped_crash, by = 'JuncID') %>% 
  left_join(intersection_bike_crash, by = 'JuncID') %>% 
  left_join(intersection_count, by = 'JuncID') %>% 
  left_join(intersection_BE, by = 'JuncID') %>% 
  left_join(intersection_landuse, by = 'JuncID') %>% 
  left_join(intersection_location, by = 'JuncID') %>% 
  left_join(intersection_traffic_facility, by = 'JuncID') %>% 
  left_join(intersection_SE, by = 'JuncID') %>%
  mutate(PerMain = MainNum/LegNum,
         PerSecond = SecondNum/LegNum,
         PerLocal = LocalNum/LegNum) %>% 
  mutate_all(~replace(., is.na(.), 0))


## block result
block_result = city_network %>% 
  st_drop_geometry() %>% 
  filter(STREET_TYP != 'Highway') %>% 
  left_join(block_ped_crash, by = 'OFT') %>% 
  left_join(block_bike_crash, by = 'OFT') %>% 
  left_join(city_network_count, by = 'OFT') %>% 
  left_join(city_network_BE, by = 'OFT') %>% 
  left_join(city_network_landuse, by = 'OFT') %>% 
  left_join(city_network_location, by = 'OFT') %>% 
  left_join(city_network_traffic_facility, by = 'OFT') %>% 
  left_join(city_network_SE, by = 'OFT') %>% 
  mutate_all(~replace(., is.na(.), 0))

## save result
write.csv(intersection_result, './result/intersection_result.csv', row.names = F)
write.csv(block_result, './result/block_result.csv', row.names = F)





































